#!/usr/bin/env node
import { readFileSync, writeFileSync, mkdirSync, existsSync, copyFileSync } from 'node:fs';
import { resolve, dirname, relative, posix } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse } from 'yaml';
import { marked } from 'marked';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SITE = resolve(ROOT, 'site');
const GH = 'https://github.com/patrickjmorris/aftergrid';
const CHECK = process.argv.includes('--check');
const PREVIEW = process.argv.includes('--allow-missing');
const skills = JSON.parse(readFileSync(resolve(SITE, 'content/skills.json'), 'utf8'));
const portableCount = skills.filter(s => s.slug !== 'setup-aftergrid').length;
// Frontmatter in each source overrides title/description; the values here are fallbacks for --allow-missing previews.
const content = [
  {source:'docs/guides/quickstart.md',route:'start/',section:'Start',title:'Catch the rollback in four rows',description:'Install one skill, paste a prompt, see whether the agent still recommends rolling back signup.'},
  {source:'docs/guides/skill-workflows.md',route:'guides/skill-workflows/',section:'Guides',title:'Choose the skill that fits the work',description:'Pick the route that matches the stuck point.'},
  {source:'docs/about.md',route:'about/',section:'About',title:'Work with me',description:'Consulting and sponsorship for teams putting analytics judgment into the agents they already use.'},
  {source:'docs/fieldnotes/ask-before-query.md',route:'fieldnotes/ask-before-query/',section:'Fieldnotes',title:'Ask before you query',description:'The useful first step rarely involves SQL.'},
  {source:'docs/fieldnotes/the-metric-moved.md',route:'fieldnotes/the-metric-moved/',section:'Fieldnotes',title:'The metric moved. Now what?',description:'Separate the arithmetic from the story.'},
  {source:'docs/fieldnotes/analysis-that-compounds.md',route:'fieldnotes/analysis-that-compounds/',section:'Fieldnotes',title:'Analysis that compounds',description:'Keep lessons the next analysis actually retrieves.'},
  {source:'docs/examples/conversion-mix.md',route:'examples/conversion-mix/',section:'Examples',title:'Conversion fell. Both channels improved.',description:'The rollback meeting. Total down, both channels up.',kind:'Synthetic lab · conversion',visual:'mix'},
  {source:'docs/examples/revenue-bridge.md',route:'examples/revenue-bridge/',section:'Examples',title:'MRR grew. The starting customers shrank.',description:'Headline +$10. Starting customers −$80. Reconcile before you celebrate.',kind:'Synthetic lab · revenue',visual:'bridge'},
  {source:'docs/examples/lesson-reuse.md',route:'examples/lesson-reuse/',section:'Examples',title:'Conversion recovered. Was it the same mechanism?',description:'Last time it was mix. Check before repeating the story.',kind:'Synthetic lab · lesson reuse',visual:'learn'},
  {source:'docs/examples/causal-claim.md',route:'examples/causal-claim/',section:'Examples',title:'Retention was 50% higher. Did onboarding cause it?',description:'A mandate and a forecast sitting on a self-selected 60% vs 40%.',kind:'Synthetic lab · review',visual:'claim'},
  {source:'docs/examples/nyc-open-data.md',route:'examples/nyc-open-data/',section:'Examples',title:'Two questions about New York',description:'Real taxi, weather, and bike data. One inconclusive answer, one descriptive one, dead ends kept.',kind:'Real open data · NYC',visual:'nyc'},
];
const CONTACT='mailto:patrickjohnmorris@gmail.com?subject=aftergrid';
const AUTHOR='https://github.com/patrickjmorris';
const sourceRoutes = new Map(content.map(x=>[x.source,x.route]));
for(const s of skills) sourceRoutes.set(`docs/skills/${s.slug}.md`,`skills/${s.slug}/`);
const esc = x => String(x ?? '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const asset = (route,file) => link(route,`assets/${file}`);
function link(from,to='') { const r=posix.relative(from || '.',to || '.'); return r ? r + (to.endsWith('/')&&!r.endsWith('/')?'/':'') : './'; }
function sourceLink(path) { return `${GH}/blob/main/${path}`; }
function readMarkdown(path) {
  const full=resolve(ROOT,path);
  if(!existsSync(full)) { if(PREVIEW) return {meta:{},body:'Content is being prepared.'}; throw new Error(`Missing site source: ${path}`); }
  let body=readFileSync(full,'utf8'),meta={};
  if(body.startsWith('---\n')) {const end=body.indexOf('\n---',4); if(end<0) throw new Error(`Unclosed frontmatter: ${path}`); meta=parse(body.slice(4,end))||{};body=body.slice(end+4).trim();}
  return {meta,body};
}
for(const page of content) Object.assign(page, readMarkdown(page.source).meta);
for(const s of skills) {
  const source=`skills/${s.slug}/SKILL.md`;
  const {meta}=readMarkdown(source);
  s.invocation=meta['disable-model-invocation']===true?'You start it':meta['user-invocable']===false?'Your agent uses it':'You or your agent';
  s.engine=s.slug==='setup-aftergrid';
}
function markdown(path,route) {
 const {body}=readMarkdown(path);
 const renderer=new marked.Renderer();
 const headingIds=new Map();
 renderer.heading=({tokens,depth,text})=>{const base=text.toLowerCase().replace(/<[^>]*>/g,'').replace(/[^a-z0-9\s-]/g,'').trim().replace(/\s+/g,'-')||'section';const count=headingIds.get(base)||0;headingIds.set(base,count+1);const id=base+(count?`-${count}`:'');return `<h${depth} id="${id}">${renderer.parser.parseInline(tokens)}</h${depth}>\n`;};
 renderer.link=({href,title,tokens})=>{
   let dest=href;
   if(href&&!/^(https?:|mailto:|#)/.test(href)) {
     const [raw,hash]=href.split('#');
     if(raw.startsWith('/')&&!raw.endsWith('.md')) dest=link(route,raw.replace(/^\/aftergrid\//,'').replace(/^\//,''))+(hash?`#${hash}`:'');
     else {const resolved=posix.normalize(posix.join(posix.dirname(path),raw));dest=sourceRoutes.has(resolved)?link(route,sourceRoutes.get(resolved))+(hash?`#${hash}`:''):sourceLink(resolved)+(hash?`#${hash}`:'');}
   }
   return `<a href="${esc(dest)}"${title?` title="${esc(title)}"`:''}>${renderer.parser.parseInline(tokens)}</a>`;
 };
 renderer.image=({href,text,title})=>{const dest=/^(https?:|data:)/.test(href)?href:`https://raw.githubusercontent.com/patrickjmorris/aftergrid/main/${posix.normalize(posix.join(posix.dirname(path),href))}`;return `<img src="${esc(dest)}" alt="${esc(text)}"${title?` title="${esc(title)}"`:''} loading="lazy">`;};
 const prepared=body.replace(/^# [^\n]+\n/,'');
 const engineAt=prepared.indexOf('## Engine Finding reference');
 const render=text=>marked.parse(text,{renderer}).replace(/<table>/g,'<div class="table-scroll"><table>').replace(/<\/table>/g,'</table></div>');
 if(path.startsWith('docs/skills/')&&engineAt>=0)return render(prepared.slice(0,engineAt))+`<details class="engine-details"><summary>Optional Engine reference</summary>${render(prepared.slice(engineAt).replace(/^## Engine Finding reference[^\n]*\n/,''))}</details>`;
 return render(prepared);
}
const symbol=`<svg viewBox="0 0 32 32" aria-hidden="true"><path fill="currentColor" d="M3 13h6v10h10v6H5a2 2 0 0 1-2-2V13Zm10-10h14a2 2 0 0 1 2 2v14h-6V9H13V3Z"/></svg>`;
function brand(route){return `<a class="brand" href="${link(route,'')}" aria-label="aftergrid home">${symbol}<span>aftergrid</span></a>`;}
function shell(route,title,description,body,current='') {
 const nav=[['Skills','skills/'],['Examples','examples/'],['Fieldnotes','fieldnotes/'],['About','about/']];
 return `<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="light"><title>${esc(title)} — aftergrid</title><meta name="description" content="${esc(description)}"><meta name="author" content="Patrick Morris"><meta property="og:title" content="${esc(title)} — aftergrid"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><link rel="canonical" href="https://patrickjmorris.github.io/aftergrid/${route}"><link rel="icon" href="${asset(route,'mark.svg')}" type="image/svg+xml"><link rel="preload" href="${asset(route,'Geist-Variable.ttf')}" as="font" type="font/ttf" crossorigin><link rel="stylesheet" href="${asset(route,'site.css')}"><script src="${asset(route,'site.js')}" defer></script></head>\n<body><a class="skip" href="#main">Skip to content</a><div class="wrap"><header class="site-header">${brand(route)}<nav class="nav" aria-label="Main navigation">${nav.map(([label,url])=>`<a href="${link(route,url)}"${current===label?' aria-current="page"':''}>${label}</a>`).join('')}<a class="github-nav" href="${GH}">GitHub<span class="external" aria-hidden="true">↗</span></a><a class="nav-start" href="${link(route,'start/')}"${current==='Start'?' aria-current="page"':''}>Start here <span aria-hidden="true">↗</span></a></nav></header><main id="main">${body}</main><footer class="site-footer"><div>${brand(route)}<p class="footer-meta">Open source · MIT · Built by <a href="${AUTHOR}">Patrick Morris</a></p></div><div class="footer-links"><a href="${link(route,'about/')}">Work with me</a><a href="${GH}">GitHub ↗</a><a href="${link(route,'guides/skill-workflows/')}">Workflows</a><a href="${sourceLink('LICENSE')}">MIT license</a><a href="${link(route,'start/')}">Install</a></div></footer></div><p class="sr" role="status" aria-live="polite" data-copy-status></p></body></html>\n`;
}
const arrow=`<span class="arrow" aria-hidden="true">↗</span>`;
function install(command='npx skills add patrickjmorris/aftergrid'){return `<div class="code-copy"><code>${esc(command)}</code><button type="button" data-copy="${esc(command)}" aria-label="Copy installation command">Copy</button></div>`;}
function sectionHead(n,label,title,desc,cta=''){return `<div class="section-head"><div><span class="label"><span class="section-number">${n}</span>${label}</span><h2>${title}</h2></div><div><p>${desc}</p>${cta}</div></div>`;}
function catalog(route){return `<div class="catalog-tools"><div class="filters" role="group" aria-label="Filter skills by stage">${['All','Frame','Analyze','Explain','Improve','Engine'].map((x,i)=>`<button type="button" data-filter="${x}" aria-pressed="${i===0}">${x}</button>`).join('')}</div><label class="search-wrap"><span class="sr">Search skills</span><input type="search" data-search placeholder="Find a skill…" autocomplete="off"></label></div><p class="catalog-count" data-result-count>${skills.length} skills</p><div class="skill-list">${skills.map(s=>`<a class="skill-row" data-skill data-phase="${s.phase}" href="${link(route,`skills/${s.slug}/`)}"><h3>${esc(s.slug)}</h3><p>${esc(s.summary)}</p><span class="phase">${s.phase}${s.engine?' · optional':''}</span><span class="row-arrow" aria-hidden="true">↗</span></a>`).join('')}</div><p class="empty" data-empty hidden>No skills match. Try a different word or stage.</p>`;}
function picture(type){
 if(type==='mix')return `<svg viewBox="0 0 290 130" role="img" aria-label="Overall conversion drops from 8.8 to 6.2 percent while both channels improve"><text x="0" y="13" fill="#52617a" font-size="10" font-family="monospace">OVERALL CONVERSION</text><text x="0" y="67" fill="#142440" font-size="44" font-weight="550">8.8<tspan font-size="20">%</tspan></text><text x="132" y="60" fill="#6a7890" font-size="26">→</text><text x="186" y="67" fill="#142440" font-size="44" font-weight="550">6.2<tspan font-size="20">%</tspan></text><line x1="0" x2="290" y1="85" y2="85" stroke="#b9cbe2"/><text x="0" y="110" fill="#52617a" font-size="11">Direct ↑ 1pp</text><text x="177" y="110" fill="#52617a" font-size="11">Paid ↑ 1pp</text></svg>`;
 if(type==='bridge'){
   const base=111,scale=.17;
   const bars=[{x:4,w:34,low:0,high:430,label:'430',name:'Before',ink:true},{x:55,w:34,low:430,high:520,label:'+90',name:'New'},{x:106,w:34,low:520,high:540,label:'+20',name:'Expand'},{x:157,w:34,low:520,high:540,label:'−20',name:'Contract',negative:true},{x:208,w:34,low:440,high:520,label:'−80',name:'Churn',negative:true},{x:259,w:29,low:0,high:440,label:'440',name:'After',ink:true}];
   const n=x=>Number(x.toFixed(1));
   return `<svg viewBox="0 0 290 130" role="img" aria-label="Revenue bridge, on a common zero baseline: 430 plus 90 new plus 20 expansion minus 20 contraction minus 80 churn equals 440"><line x1="0" x2="290" y1="111" y2="111" stroke="#b9cbe2"/>${bars.map(b=>`<rect x="${b.x}" y="${n(base-b.high*scale)}" width="${b.w}" height="${n((b.high-b.low)*scale)}" fill="${b.ink?'#142440':b.negative?'#b4c3d8':'#658dbb'}"/><text x="${n(b.x+b.w/2)}" y="${n(base-b.high*scale-7)}" font-family="monospace" font-size="10" text-anchor="middle" fill="#52617a">${b.label}</text><text x="${n(b.x+b.w/2)}" y="127" font-size="8" text-anchor="middle" fill="#52617a">${b.name}</text>`).join('')}</svg>`;
 }
 if(type==='learn')return `<svg viewBox="0 0 290 130" role="img" aria-label="Conversion recovers from 6.2 to 8.0 percent after a prior mix-shift lesson is retrieved and tested"><text x="0" y="13" fill="#52617a" font-size="10" font-family="monospace">FOLLOW-UP CONVERSION</text><text x="0" y="67" fill="#142440" font-size="44" font-weight="550">6.2<tspan font-size="20">%</tspan></text><text x="132" y="60" fill="#6a7890" font-size="26">→</text><text x="186" y="67" fill="#142440" font-size="44" font-weight="550">8.0<tspan font-size="20">%</tspan></text><line x1="0" x2="290" y1="85" y2="85" stroke="#b9cbe2"/><text x="0" y="110" fill="#52617a" font-size="11">Lesson retrieved</text><text x="155" y="110" fill="#52617a" font-size="11">Mix + paid rate, not a reverse</text></svg>`;
 if(type==='claim')return `<svg viewBox="0 0 290 130" role="img" aria-label="Completers retain at 60 percent, non-completers at 40 percent; a causal plus-50-percent claim is unsupported"><text x="0" y="13" fill="#52617a" font-size="10" font-family="monospace">WEEK-4 RETENTION</text><text x="0" y="67" fill="#142440" font-size="44" font-weight="550">60<tspan font-size="20">%</tspan></text><text x="108" y="60" fill="#6a7890" font-size="22">vs</text><text x="148" y="67" fill="#142440" font-size="44" font-weight="550">40<tspan font-size="20">%</tspan></text><line x1="0" x2="290" y1="85" y2="85" stroke="#b9cbe2"/><text x="0" y="110" fill="#52617a" font-size="11">Observed association</text><text x="168" y="110" fill="#79542b" font-size="11">Not a cause</text></svg>`;

 return `<svg viewBox="0 0 290 130" role="img" aria-label="Two real New York analyses: congestion pricing inconclusive; member e-bike share answered"><g stroke="#c7d6e8" stroke-width="1"><path d="M0 22H290M0 52H290M0 82H290M0 112H290M25 0V130M65 0V130M105 0V130M145 0V130M185 0V130M225 0V130M265 0V130"/></g><rect x="16" y="22" width="258" height="40" rx="3" fill="#fcfcfa" stroke="#c7d6e8"/><text x="29" y="47" fill="#142440" font-size="11">Congestion pricing</text><text x="256" y="47" text-anchor="end" fill="#79542b" font-size="10">Inconclusive</text><rect x="16" y="75" width="258" height="40" rx="3" fill="#fcfcfa" stroke="#c7d6e8"/><text x="29" y="100" fill="#142440" font-size="11">Member e-bike share</text><text x="256" y="100" text-anchor="end" fill="#27684c" font-size="10">Answered</text></svg>`;
}
function cases(route){return `<div class="case-grid">${content.filter(x=>x.section==='Examples').map(x=>`<a class="case" href="${link(route,x.route)}"><div class="case-picture">${picture(x.visual)}</div><span class="label">${x.kind}</span><h3>${esc(x.title)}</h3><p>${esc(x.description)}</p>${x.visual==='nyc'?'<span class="case-status">Draft Findings · not publication-approved</span>':''}<span class="text-link">Follow the analysis</span></a>`).join('')}</div>`;}
function notes(route){return `<div class="notes-list">${content.filter(x=>x.section==='Fieldnotes').map((x,i)=>`<a class="note-row" href="${link(route,x.route)}"><span class="note-index">0${i+1}</span><div><h3>${esc(x.title)}</h3><p>${esc(x.description)}</p></div><span class="row-arrow" aria-hidden="true">↗</span></a>`).join('')}</div>`;}
function closing(route){return `<section class="closing"><h2>Next time a metric moves,<br>don’t let the average run the meeting.</h2><div><p>Install one skill. Paste the four-row prompt. See whether the agent still recommends the rollback.</p><a class="button primary" href="${link(route,'start/')}">Try the conversion trap ${arrow}</a></div></section>`;}
function maker(route){return `<section class="section" id="work-with-me">${sectionHead('05','From the maintainer','Built by an analyst.<br>Available for hire.','I’m Patrick Morris. I made these because the agent answers reaching product and growth decisions were fast, confident, and wrong in ways an analyst catches in a minute.',`<a class="text-link" href="${link(route,'about/')}">About the project</a>`)}<div class="maker-grid"><a href="${link(route,'about/#consulting')}"><span class="label">Consulting</span><h3>Put the judgment in your team’s agent.</h3><p>Metric definitions a second analyst would apply the same way. A review step before numbers reach a decision. Lessons the next analysis retrieves. Pilots are open.</p><span class="text-link">Work with me</span></a><a href="${link(route,'about/#sponsorship')}"><span class="label">Sponsorship</span><h3>Fund the public skills and examples.</h3><p>A named line here and in the docs. Nothing commercial inside a Finding, and no sponsor touches a metric approval.</p><span class="text-link">Sponsor aftergrid</span></a></div></section>`;}
function specimen(route){
 const csv='https://raw.githubusercontent.com/patrickjmorris/aftergrid/main/examples/skills-lab/data/conversion.csv';
 const explain=`Use shape-narrative on this result: overall conversion fell from 8.8% to 6.2% while direct and paid each improved 1pp. Data: ${csv}. Lead with whether we should roll back signup.`;
 const diagnose=`/diagnose-change Conversion fell from 8.8% to 6.2%. Should we roll back signup? Use ${csv}. Reproduce the movement. Separate mix from within-channel change. Show the calculations. Do not recommend a rollback from the aggregate alone.`;
 const review=`Use analysis-review on the claim “conversion fell, so both channels got worse — roll back signup.” Data: ${csv}. Check channel rates, mix, and the denominator. Name the smallest correction before someone acts.`;
 return `<div class="specimen-wrap"><div class="specimen"><div class="specimen-top"><span class="label">Tomorrow’s standup. Four rows.</span><span class="specimen-mark" aria-hidden="true">⌗</span></div><div class="scenario-tabs" role="group" aria-label="Choose an analysis task"><button data-scenario-tab aria-pressed="true" aria-controls="scenario-diagnose">Diagnose a change</button><button data-scenario-tab aria-pressed="false" aria-controls="scenario-explain">Explain it</button><button data-scenario-tab aria-pressed="false" aria-controls="scenario-review">Review it</button></div><div class="scenario-panel" id="scenario-diagnose" data-scenario-panel><h2 class="scenario-question">Conversion fell.<br>Both channels improved.</h2><div class="scenario-chart"><div class="chart-row"><span>Before</span><div class="chart-track"><div class="chart-fill" style="width:88%"></div></div><strong>8.8%</strong></div><div class="chart-row"><span>After</span><div class="chart-track"><div class="chart-fill current" style="width:62%"></div></div><strong>6.2%</strong></div><p class="chart-caption">Tempting call: roll back signup. The weights moved, not the rates.</p></div><p class="scenario-prompt"><span class="slash">/diagnose-change</span> Should we roll back signup? Separate mix from within-channel change.</p><button class="tiny-copy" data-copy="${esc(diagnose)}">Copy the prompt — no clone needed ↗</button></div><div class="scenario-panel" id="scenario-explain" data-scenario-panel hidden><h2 class="scenario-question">The average changed.<br>The story needs context.</h2><ul class="mini-checks"><li><span>−3.6pp</span> Mix pulled conversion down.</li><li><span>+1.0pp</span> Each channel improved.</li><li><span>−2.6pp</span> Together they are the total. Not a product cause.</li></ul><p class="scenario-prompt"><span class="slash">shape-narrative</span> Lead with the decision: do not roll back on this aggregate.</p><button class="tiny-copy" data-copy="${esc(explain)}">Copy the prompt — no clone needed ↗</button></div><div class="scenario-panel" id="scenario-review" data-scenario-panel hidden><h2 class="scenario-question">“Both channels got worse.”<br>Does that claim hold?</h2><ul class="mini-checks"><li><span>↳</span> Direct: 10% → 11%.</li><li><span>↳</span> Paid: 4% → 5%.</li><li><span>!</span> An aggregate drop is not a rollback brief.</li></ul><p class="scenario-prompt"><span class="slash">analysis-review</span> Kill the rollback claim before the meeting.</p><button class="tiny-copy" data-copy="${esc(review)}">Copy the prompt — no clone needed ↗</button></div><a class="specimen-footer" href="${link(route,'start/')}">Install one skill and run it <span aria-hidden="true">↗</span></a></div><p class="specimen-note">Four-row CSV on GitHub · prompt hits the live file · not a model transcript</p></div>`;
}
function home(){const r='';return shell(r,'Conversion fell. Rollback is the wrong call.','Open-source analytics skills for the agent you already use. Catch a mix-shift, a hidden churn, or a causal overclaim before the meeting.',`<section class="hero"><div class="hero-copy"><p class="eyebrow">Analytics skills for your AI agent</p><h1>Conversion fell.<br><span>Rollback is the wrong call.</span></h1><p class="intro">Both channels improved. Mix did the damage. One skill, four rows, two minutes — before someone acts on the average.</p><div class="hero-actions"><a class="button primary" href="${link(r,'start/')}">Try this case ${arrow}</a><a class="button quiet" href="${link(r,'examples/')}">See the examples</a></div><p class="hero-foot">No warehouse. No Engine. Copy the prompt; the CSV is already on GitHub.</p></div>${specimen(r)}</section><section class="install-strip" aria-label="Install aftergrid"><div><strong>Install the skill. Paste the prompt.</strong><p>diagnose-change is enough for this case. The rest of the set is one command.</p></div>${install('npx skills add patrickjmorris/aftergrid --skill diagnose-change')}</section><section class="section">${sectionHead('01','The traps','The average will<br>run the meeting.','These are the moments an agent without judgment ships the wrong story.')}<div class="workflow">${[['Vague ask','“Did onboarding work?” is four questions.','grill-question'],['Number moved','Reproduce it. Mix vs rate. Then talk.','diagnose-change'],['Draft too sure','60% vs 40% is not a mandate.','analysis-review'],['Same mistake twice','Keep the lesson. Retrieve it next time.','learn-from-analysis']].map(([t,d,s],i)=>`<a href="${link(r,`skills/${s}/`)}"><span class="step">0${i+1}<span aria-hidden="true">↗</span></span><h3>${t}</h3><p>${d}</p><span class="skill-name">${s}</span></a>`).join('')}</div><div class="section-bottom"><p>Then use the same skills on your CSV, notebook, or warehouse.</p><a class="text-link" href="${link(r,'guides/skill-workflows/')}">Choose a workflow</a></div></section><section class="section" id="skills">${sectionHead('02','The skills','Pick the skill<br>the stuck point needs.',`${portableCount} portable skills, plus optional Engine setup. Unsure which? ask-aftergrid names one and stops.`)} ${catalog(r)}</section><section class="section">${sectionHead('03','In practice','See the miss,<br>then the catch.','A rollback on a mix-shift, growth that hid churn, a causal headline on self-selected retention, and a follow-up that has to re-test last week’s lesson.',`<a class="text-link" href="${link(r,'examples/')}">Explore the examples</a>`)}${cases(r)}</section><section class="section">${sectionHead('04','Fieldnotes','The habits<br>behind the skills.','Ask first. Diagnose the move. Keep what you learned.')} ${notes(r)}</section>${maker(r)}${closing(r)}`);}
const outputs=new Map();
function emit(route,html){outputs.set(`${route}index.html`,html);}
emit('',home());
emit('skills/',shell('skills/','The skill library',`${skills.length} analytics skills, from choosing the next procedure to keeping the lesson. Browse by stage or search by task.`,`<header class="page-hero"><p class="eyebrow">The skill library</p><h1>Pick the job,<br>then the skill.</h1><p class="intro">Sharpen a question, inspect data, explain a change, or challenge a draft. Start with ask-aftergrid if you are unsure.</p></header><section class="listing-content">${catalog('skills/')}<aside class="engine-note"><div><h3>Skills first. Engine when you need it.</h3><p>${portableCount} skills work with your existing tools. The optional Engine adds typed Findings, evidence binding, and Checks.</p></div><a class="text-link" href="${link('skills/','skills/setup-aftergrid/')}">About Engine setup</a></aside></section>`,'Skills'));
for(const s of skills){const r=`skills/${s.slug}/`;emit(r,shell(r,`${s.slug} — ${s.summary}`,s.summary,`<header class="page-hero"><a class="breadcrumb" href="${link(r,'skills/')}">← All skills</a><p class="eyebrow">${s.phase} / ${s.engine?'Optional Engine':'Portable skill'}</p><h1>${esc(s.slug)}</h1><p class="intro">${esc(s.summary)}</p><div class="meta"><span class="tag blue">${s.invocation}</span><span class="tag">${s.engine?'Engine required':'Your existing data tools'}</span><span class="tag">Open source · MIT</span></div></header><div class="reading-layout"><article class="reading article-lede">${markdown(`docs/skills/${s.slug}.md`,r)}<div class="article-footer"><a href="${link(r,'skills/')}"><span class="label">Keep exploring</span>← Back to the skill library</a><a href="${link(r,'start/')}"><span class="label">Try it</span>Install your first skill ↗</a></div></article><aside class="aside"><div><span class="label">Try this prompt</span><pre>${esc(s.prompt)}</pre><button class="tiny-copy" data-copy="${esc(s.prompt)}">Copy prompt ↗</button><p>Use <code>$skill-name</code> in Codex, or your host’s invocation syntax. You can request model-invoked skills in plain language.</p><h2>What you leave with</h2><p>${esc(s.outcome)}</p></div><div class="aside-section"><span class="label">Install this skill</span><pre>npx skills add patrickjmorris/aftergrid --skill ${s.slug}</pre><button class="tiny-copy" data-copy="npx skills add patrickjmorris/aftergrid --skill ${s.slug}">Copy install command ↗</button><p>Installing copies Markdown. The skill uses the tools and permissions your agent already has.</p><a class="aside-link" href="${sourceLink(`skills/${s.slug}/SKILL.md`)}">Read the source</a><a class="aside-link" href="${link(r,'start/')}">Installation guide</a><a class="aside-link" href="${link(r,'guides/skill-workflows/')}">Put skills together</a><a class="aside-link" href="${link(r,'about/')}">Work with Patrick</a></div></aside></div>`,'Skills'));}
emit('examples/',shell('examples/','You have sat these meetings','A rollback on a mix-shift, growth that hid churn, a causal headline, and a recovered metric that still needs last week’s lesson.',`<header class="page-hero"><p class="eyebrow">Examples</p><h1>You have sat<br>these meetings.</h1><p class="intro">Rollback on the average. Growth that hid churn. A 50% lift treated as a mandate. A recovered metric that still needs last week’s lesson.</p></header><section class="listing-content"><div class="index-intro"><p>Synthetic labs are labeled. Real Findings show publication status separately from outcome.</p><a class="text-link" href="${GH}/tree/main/examples">Source data & code</a></div>${cases('examples/')}</section>${closing('examples/')}`,'Examples'));
emit('fieldnotes/',shell('fieldnotes/','Ask first. Diagnose the move. Keep the lesson.','The habits behind the skills — for the meeting after this one.',`<header class="page-hero"><p class="eyebrow">Fieldnotes</p><h1>Ask first.<br>Then keep what you learned.</h1><p class="intro">Three essays. Each names a failure mode the skills are built to catch.</p></header><section class="listing-content">${notes('fieldnotes/')}</section>${closing('fieldnotes/')}`,'Fieldnotes'));
function practiceAside(r){return `<aside class="aside"><div><span class="label">Put it into practice</span><h2>One question.<br>One useful next step.</h2><p>Install a skill and try it with the data, context, and tools you already have.</p><a class="aside-link" href="${link(r,'skills/')}">Browse the skills</a><a class="aside-link" href="${link(r,'guides/skill-workflows/')}">Choose a workflow</a><a class="aside-link" href="${link(r,'start/')}">Installation guide</a></div><div class="aside-section"><span class="label">Explore the examples</span>${content.filter(x=>x.section==='Examples'&&x.route!==r).map(x=>`<a class="aside-link" href="${link(r,x.route)}">${esc({mix:'Conversion & mix',bridge:'The revenue bridge',learn:'Lesson reuse',claim:'Causal overclaim',nyc:'New York open data'}[x.visual]||x.title)}</a>`).join('')}</div></aside>`;}
function contactAside(r){return `<aside class="aside"><div><span class="label">Get in touch</span><h2>Bring the meeting<br>you’re trying to get right.</h2><p>One email. Say what decision is on the table and what the agent currently tells you.</p><a class="aside-link" href="${CONTACT}">Email Patrick</a><a class="aside-link" href="${AUTHOR}">GitHub profile</a></div><div class="aside-section"><span class="label">Before you write</span><a class="aside-link" href="${link(r,'start/')}">Try the four-row case</a><a class="aside-link" href="${link(r,'examples/')}">Read the worked examples</a></div></aside>`;}
for(const p of content){const r=p.route;emit(r,shell(r,p.title,p.description,`<header class="page-hero">${p.section==='Examples'||p.section==='Fieldnotes'?`<a class="breadcrumb" href="${link(r,p.section.toLowerCase()+'/')}">← ${p.section}</a>`:''}<p class="eyebrow">${esc(p.kicker||p.section)}</p><h1>${esc(p.title)}</h1><p class="intro">${esc(p.description)}</p></header><div class="reading-layout"><article class="reading article-lede">${markdown(p.source,r)}<div class="article-footer"><a href="${link(r,'skills/')}"><span class="label">Find your next step</span>Browse the skills ↗</a><a href="${sourceLink(p.source)}"><span class="label">In the open</span>Read this page on GitHub ↗</a></div></article>${p.section==='About'?contactAside(r):practiceAside(r)}</div>`,p.section));}
outputs.set('example-finding/index.html',readFileSync(resolve(ROOT,'fixtures/instance/analytics/findings/2026-07-20-onboarding-checklist-retention/render/finding.html'),'utf8'));
outputs.set('assets/mark.svg',`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><path fill="#142440" d="M3 13h6v10h10v6H5a2 2 0 0 1-2-2V13Zm10-10h14a2 2 0 0 1 2 2v14h-6V9H13V3Z"/></svg>\n`);
outputs.set('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${[...outputs.keys()].filter(x=>x.endsWith('index.html')).map(x=>`<url><loc>https://patrickjmorris.github.io/aftergrid/${x.replace(/index.html$/,'')}</loc></url>`).join('')}</urlset>\n`);
outputs.set('robots.txt','User-agent: *\nAllow: /\nSitemap: https://patrickjmorris.github.io/aftergrid/sitemap.xml\n');
outputs.set('content/generated-pages.json',JSON.stringify([...outputs.keys()].filter(x=>x.endsWith('index.html')),null,2)+'\n');
let drift=[];
for(const [path,value] of outputs){const full=resolve(SITE,path);if(CHECK){if(!existsSync(full)||readFileSync(full,'utf8')!==value)drift.push(path);}else{mkdirSync(dirname(full),{recursive:true});writeFileSync(full,value);}}
for(const [from,to] of [['fonts/geist/Geist-Variable.ttf','assets/Geist-Variable.ttf'],['fonts/geist/OFL.txt','assets/OFL.txt']]){const source=resolve(ROOT,from),target=resolve(SITE,to);if(CHECK){if(!existsSync(target)||!readFileSync(source).equals(readFileSync(target)))drift.push(to);}else copyFileSync(source,target);}
if(drift.length){console.error(`Site build drift:\n${drift.map(x=>'  '+x).join('\n')}\nRun node scripts/build-site.mjs and commit the generated files.`);process.exitCode=1;}else console.log(`${CHECK?'Verified':'Built'} ${outputs.size} deterministic site files${PREVIEW?' (missing sources allowed for local composition)':''}.`);
