// Cached render outputs are not evidence. Before anything is published, re-render the Finding from its validated
// source into a throwaway copy of the Instance and compare the bytes with what is sitting in `render/`. A
// difference is `tampered_output`: the files on disk are discarded and the regenerated bytes are what publication
// uses. PNG previews are excluded on purpose (see docs/contracts/publication.md).
import { cpSync, existsSync, lstatSync, mkdtempSync, readFileSync, readdirSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { isAbsolute, join, relative, resolve, sep } from "node:path";
import type { Problem } from "../report.ts";
// @ts-ignore: shared path containment.
import { safePath, ContractError } from "../../scripts/fixture-safety.mjs";
import { findInstance } from "../instance.ts";
import { render } from "../commands/render.ts";

export type OutputVerification = {
  /**
   * verified: bytes match. tampered: they do not (`tampered_output`). not_verifiable: the source could not be
   * re-rendered at all, which is reported as `render_error` — an unverifiable output is never called a tampered one.
   */
  status: "verified" | "tampered" | "not_verifiable";
  /** The output paths, relative to the Finding directory, that were compared. */
  compared: string[];
  problems: Problem[];
  /** Freshly rendered bytes keyed by the same relative paths. Publication uses these, never the files on disk. */
  regenerated: Map<string, Buffer>;
};

const COMPARED = (name: string) => name === "finding.html" || name.endsWith(".svg");

/**
 * Re-render `dir` into a temporary copy of its Instance and compare `render/finding.html` and every chart SVG byte
 * for byte. The copy carries the Instance policy, Reader profiles and definitions the render needs, but not the
 * sibling Findings and not the cached `render/` directory being checked.
 */
export async function verifyGeneratedOutputs(dir: string, opts: { generatedAt?: string } = {}): Promise<OutputVerification> {
  const target = resolve(dir);
  const problems: Problem[] = [];
  const out = (status: OutputVerification["status"], compared: string[] = [], regenerated = new Map<string, Buffer>()): OutputVerification => ({ status, compared, problems, regenerated });

  const instance = findInstance(target);
  if (!instance) {
    problems.push({ category: "missing_file", location: target, message: "no aftergrid.yaml above this Finding, so it cannot be re-rendered from a consistent Instance view", remedy: "run this inside an Instance" });
    return out("not_verifiable");
  }
  const rel = relative(instance.root, target);
  if (!rel || isAbsolute(rel) || rel.split(sep).includes("..")) {
    problems.push({ category: "unsafe_path", location: target, message: "the Finding directory is not contained in its Instance", remedy: "keep Findings under the Instance root" });
    return out("not_verifiable");
  }

  const stage = mkdtempSync(join(tmpdir(), "ag-publication-"));
  try {
    const parts = rel.split(sep), leaf = parts[parts.length - 1]!, prefix = parts.slice(0, -1);
    const copyRoot = join(stage, "instance");
    cpSync(instance.root, copyRoot, {
      recursive: true,
      filter: (src) => {
        const p = relative(instance.root, src);
        if (!p) return true;
        const seg = p.split(sep);
        // Skip the sibling Findings: they cost time and nothing here reads them. With an empty prefix the Finding
        // sits directly under the Instance root, where its "siblings" are the Instance itself — aftergrid.yaml,
        // definitions/, readers.md — so nothing is skipped and the whole Instance is staged.
        if (prefix.length > 0 && seg.length > prefix.length && prefix.every((x, i) => seg[i] === x) && seg[prefix.length] !== leaf) return false;
        // Skip the cached outputs under test: the copy must be re-rendered from source alone.
        if (seg.length > parts.length && parts.every((x, i) => seg[i] === x) && seg[parts.length] === "render") return false;
        return true;
      },
    });

    // Vega numbers SVG def ids from a process-global counter. Reset it so a re-render reproduces the canonical
    // output of a fresh `aftergrid render` byte for byte rather than differing only in clip-path numbering.
    const { resetSVGDefIds } = await import("vega");
    resetSVGDefIds();
    const copyDir = join(copyRoot, rel);
    const report = await render({ dir: copyDir, png: false, generatedAt: opts.generatedAt });
    if (report.errors.length) {
      problems.push(...report.errors);
      // "Could not verify" is not "was tampered with": a re-render that fails says nothing about the bytes on disk.
      problems.push({ category: "render_error", location: `${rel}/render`, message: "the Finding could not be re-rendered from its source, so its cached outputs could not be compared and cannot be trusted or replaced", remedy: "fix the errors above; publication never falls back to the files already in render/" });
      return out("not_verifiable");
    }

    const regenerated = new Map<string, Buffer>();
    const freshDir = join(copyDir, "render");
    for (const name of existsSync(freshDir) ? readdirSync(freshDir).sort() : []) {
      if (COMPARED(name)) regenerated.set(`render/${name}`, readFileSync(join(freshDir, name)));
    }

    const cached = new Map<string, Buffer | null>();
    let cachedDir: string | null = null;
    try { cachedDir = safePath(target, "render"); } catch (e) {
      problems.push({ category: (e as any).category ?? "unsafe_path", location: `${rel}/render`, message: (e as Error).message });
      return out("not_verifiable", [...regenerated.keys()], regenerated);
    }
    if (existsSync(cachedDir)) for (const name of readdirSync(cachedDir).sort()) {
      if (!COMPARED(name)) continue; // Hand-authored references such as finding.template.html are not generated.
      const key = `render/${name}`;
      try {
        const p = safePath(target, key);
        cached.set(key, lstatSync(p).isFile() ? readFileSync(p) : null);
      } catch (e) {
        cached.set(key, null);
        problems.push({ category: e instanceof ContractError ? (e as any).category : "unsafe_path", location: key, message: (e as Error).message });
      }
    }

    const compared = [...new Set([...regenerated.keys(), ...cached.keys()])].sort();
    for (const key of compared) {
      const fresh = regenerated.get(key), disk = cached.get(key);
      if (!fresh) {
        problems.push({ category: "tampered_output", location: key, message: "this file is in render/ but the renderer does not produce it; it was not generated from this Finding's source", remedy: "delete it and regenerate the outputs with `aftergrid render`" });
      } else if (disk === undefined) {
        problems.push({ category: "tampered_output", location: key, message: "the renderer produces this file but it is missing from the cached outputs", remedy: "regenerate the outputs with `aftergrid render` before publishing" });
      } else if (disk === null || !disk.equals(fresh)) {
        problems.push({ category: "tampered_output", location: key, message: `the cached output does not match a re-render of the validated source (${disk === null ? "unreadable" : `${disk.length} bytes on disk, ${fresh.length} bytes regenerated`})`, remedy: "discard the cached file and regenerate the outputs with `aftergrid render`; publication uses only regenerated bytes" });
      }
    }
    return out(problems.length ? "tampered" : "verified", compared, regenerated);
  } catch (e) {
    problems.push({ category: e instanceof ContractError ? (e as any).category : "render_error", location: rel, message: `the outputs could not be verified: ${(e as Error).message}`, remedy: "publication never treats an unverifiable output as good" });
    return out("not_verifiable");
  } finally {
    rmSync(stage, { recursive: true, force: true });
  }
}
